#---------------------------------------------------
# GitHub Action Part-1 Basics
#
# Copyleft (c) by Andrey Ososkov 2024.
#---------------------------------------------------
name: My-GitHubActions-Basics
on: 
  push:
    branches: 
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message
      run: echo "Hello World from Testing job"
  
  my_deploy:
    runs-on: ubuntu-latest 
    needs: [my_testing]

    steps:
    - name: Print Hello Message
      run: echo "Hello World from Deploy job"
